/arm: 
    # Publish all joint states-----------------------------------------------------

    joint_state_controller:
        type: joint_state_controller/JointStateController
        publish_rate: 50  

    # Forward Position Controllers ------------------------------------------------------
    joint0_position_controller:
        type: position_controllers/JointPositionController
        joint: j0
        
        
    joint1_position_controller:
        type: position_controllers/JointPositionController
        joint: j1
        

    joint2_position_controller:
        type: position_controllers/JointPositionController
        joint: j2
        

    joint3_position_controller:
        type: position_controllers/JointPositionController
        joint: j3
        